packages:
  - .
  - '!tests/fixtures/**'

onlyBuiltDependencies:
  - esbuild
  - lightningcss

overrides:
  'diff@^7': '^8.0.3'
  'serialize-javascript@^6': '^7.0.5'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - 'postcss' # Needed for version 8.5.15. Remove after 2026-05-22T09:51:29Z

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
