packages:
  - .
  - '!tests/fixtures/**'

allowBuilds:
  'esbuild': true
  'lightningcss': true
  'snyk': true
  'unrs-resolver': true

overrides:
  '@typescript-eslint/utils@^8.32': '^8.57.0'
  'diff@^7': '^8.0.3'
  'serialize-javascript@^6': '^7.0.5'
  'esbuild@^0.27': '^0.28.1'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
verifyDepsBeforeRun: false
